# Generated by Django 3.1.3 on 2020-12-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='P4',
        ),
        migrations.AddField(
            model_name='item',
            name='intro',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='item',
            name='reasons',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='P1',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='P2',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='P3',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='features1',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='features2',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='fslink',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='seotags',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='storelink',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
