# Generated by Django 3.1.3 on 2020-12-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20201206_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='insertTOP',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(default=1607266496, primary_key=True, serialize=False),
        ),
    ]
