# Generated by Django 3.1.3 on 2020-12-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_auto_20201206_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(default=1607266742, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.IntegerField(default=1607266742, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='insertTOP',
            field=models.BooleanField(blank=True),
        ),
    ]
