# Generated by Django 3.1.3 on 2020-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20201206_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.IntegerField(default=1607266931, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.IntegerField(default=1607266931, primary_key=True, serialize=False),
        ),
    ]
