# Generated by Django 3.1.3 on 2020-12-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_auto_20201206_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.IntegerField(default=100000000, primary_key=True, serialize=False),
        ),
    ]
