# Generated by Django 3.1.3 on 2020-12-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_auto_20201206_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.IntegerField(default=1607268523, primary_key=True, serialize=False),
        ),
    ]
