# Generated by Django 3.1.3 on 2020-12-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_auto_20201206_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
