# Generated by Django 3.1.3 on 2020-12-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_auto_20201206_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='insertTOP',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
