# Generated by Django 3.1.3 on 2020-12-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_auto_20201206_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shortname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
