# Generated by Django 3.1.3 on 2020-12-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_item_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='P1',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='P2',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='P3',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='features1',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='features2',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='intro',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='reasons',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='seotags',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='storelink',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
