# Generated by Django 3.1.3 on 2020-12-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_auto_20201207_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Compatibility',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
