# Generated by Django 3.1.3 on 2020-12-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_item_compatibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='latestversion',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
