# Generated by Django 3.1.3 on 2020-12-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_auto_20201207_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='more',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
