# Generated by Django 3.1.3 on 2020-12-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_item_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='querypurpose',
            field=models.ManyToManyField(related_name='query', to='root.MainTag'),
        ),
    ]
