# Generated by Django 3.1.3 on 2020-12-08 07:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_auto_20201208_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to='files/'),
        ),
    ]
