# Generated by Django 3.1.3 on 2020-12-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0027_auto_20201208_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='storelink',
            new_name='assetstorelink',
        ),
    ]
