# Generated by Django 3.1.3 on 2020-12-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0029_item_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='AUTOGENRATE',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
