# Generated by Django 3.1.3 on 2020-12-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_auto_20201208_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='support_versions',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
