# Generated by Django 3.1.3 on 2020-12-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0032_item_support_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
